### ISSUE TITLE
没有按照 Characteristics 里的 FPS 回调获取画面

### ISSUE THREAD

**Issue by yangjieshao** [kekyo/FlashCap#30]
![image](https://user-images.githubusercontent.com/3275834/209793572-e8e80ddb-b9d8-41df-ae1d-4e174cbd1d5c.png)
```

private static async void Start(int selectCameraIndex,int selectCharacteristicsIndex)
{
	var devices = new CaptureDevices();
	var descriptor0 = devices.EnumerateDescriptors().ElementAt(selectCameraIndex);

	Console.WriteLine($"Selected camera :{descriptor0.Name}  Characteristic:{descriptor0.Characteristics[selectCharacteristicsIndex]}");
	using var device = await descriptor0.OpenAsync(
		descriptor0.Characteristics[selectCharacteristicsIndex],
		  bufferScope =>
		{
			Console.WriteLine($"Timestamp:{bufferScope.Buffer.Timestamp}  FrameIndex:{bufferScope.Buffer.FrameIndex}");
		});

	await device.StartAsync();

	Console.ReadKey();

	await device.StopAsync();
}
```
使用的是 1 FPS 的 Characteristic 实际是按照 25 FPS 返回的画面

**Comment by yangjieshao** [comment]
![1672222189956](https://user-images.githubusercontent.com/3275834/209795836-a4e98208-e530-443b-81cd-2b0240e63756.jpg)
刚才又看了下 获取的图像大小也与设置的 Characteristic 不一致
```

private static async void Start(int selectCameraIndex,int selectCharacteristicsIndex)
{
	var devices = new CaptureDevices();
	var descriptor0 = devices.EnumerateDescriptors().ElementAt(selectCameraIndex);
	bool checkSize = false;

	Console.WriteLine($"Selected camera :{descriptor0.Name}  Characteristic:{descriptor0.Characteristics[selectCharacteristicsIndex]}");
	using var device = await descriptor0.OpenAsync(
		descriptor0.Characteristics[selectCharacteristicsIndex],
		  bufferScope =>
		{
			if(!checkSize)
			{
				checkSize = true;
				byte[] image = bufferScope.Buffer.ExtractImage();

				var ms = new MemoryStream(image);
				var bitmap = Bitmap.FromStream(ms);
				Console.WriteLine($"Size:{bitmap.Size}");
				bitmap.Dispose();
			}

			Console.WriteLine($"Timestamp:{bufferScope.Buffer.Timestamp}  FrameIndex:{bufferScope.Buffer.FrameIndex}");
		});

	// Start processing:
	await device.StartAsync();

	Console.ReadKey();

	await device.StopAsync();

}
```

**Comment by kekyo** [comment]
@yangjieshao I have added a function to the Avalonia sample code to display actual FPS measurements, so please try it out in your environment. It may be possible that the camera device you are using is returning lied information.

#31 f3e4f14e1f7eed829e8467f34d40dc8bb0b7be03

The following example is for a device I have. "FPS=nnn/mmm" is the actual value, the first value is able to reach the callback delegate, and the second value is able to reach the FlashCap internals. A smaller difference indicates a smaller of frame drops that can be recognized.

* There is a possibility that there are other frame drops that are not recognized by FlashCap.
* The following tests were done on Windows because Windows was the only environment available for testing right just now. Therefore, it is possible that there may be a problem with V4L2...

### Logicool Webcam C930e

The characteristics on this camera seems accurate.

1920x1080 JPEG 30fps

![image](https://user-images.githubusercontent.com/6181948/209824803-ae682991-1dcd-4389-af48-83292ec51703.png)

1920x1080 YUYV 5fps

![image](https://user-images.githubusercontent.com/6181948/209824910-fbe834ab-a2b4-4957-bbf7-9642a07d00b8.png)

### HD Webcam eMeet C970L

The low FPS characteristics are very suspicious.

1920x1080 JPEG 30fps

![image](https://user-images.githubusercontent.com/6181948/209825174-8ae2e156-6bba-4713-8d75-e25d6f796573.png)

1920x1080 JPEG 1fps

![image](https://user-images.githubusercontent.com/6181948/209825414-0c9447a0-7284-4212-9404-b1b5ebcf0b5f.png)

### Cam Link 4K

FHD/60fps.

![image](https://user-images.githubusercontent.com/6181948/209826367-16ed7bc9-09b8-4a67-868e-7862667601d3.png)

**Comment by kekyo** [comment]
In 55bb1743c9185906115ecfe17ec13b2e11af2843, add SKBitmap statistics. Logicool camera is valid.

![image](https://user-images.githubusercontent.com/6181948/209827498-deccd619-90cb-4b0c-b5ac-f843b6bd595e.png)

**Comment by kekyo** [comment]
eMeet C970L 1fps is returned SKBitmap: 640x480

![image](https://user-images.githubusercontent.com/6181948/209829377-fc521ad8-4be5-4f4d-94ef-e12e145d7eb9.png)

**Comment by yangjieshao** [comment]
thanks
I will buy a new camera for testing
The camera used before is a cheap camera with a price of more than 10 RMB. It may indeed return false information

**Comment by kekyo** [comment]
Note: I imagine, looking at another existing applications, that sometimes 1fps and/or 5fps are not present in the choices in the selection list, so these may have been excluded from the list as an apparently unusual characteristic by these application.

**Comment by kekyo** [comment]
@yangjieshao  If it was obviously strange, please reopen it 😄
